name: Build OpenPoster

on:
  workflow_dispatch:
  push:
    branches:
      # problem? :P
      - main

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    if: startsWith(github.event.head_commit.message, '[build]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: the real deal
        run: |
          for file in ui/*.ui; do
            xmllint --noout "$file" || {
              echo "please kindly check $file thank you"
              exit 1
            }
          done
          
  build:
    name: Build (${{ matrix.config.name }})
    needs: [lint]
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: macos-intel
            os: macos-13
            python: python3
            cmds: |
              cd dist
              zip -r -y "OpenPoster-${{ matrix.config.name }}.zip" OpenPoster.app
          - name: macos-arm
            os: macos-latest
            python: python3
            cmds: |
              cd dist
              zip -r -y "OpenPoster-${{ matrix.config.name }}.zip" OpenPoster.app
          - name: windows
            os: windows-latest
            python: python
            cmds: |
              cd dist
              Compress-Archive -Path OpenPoster -DestinationPath "OpenPoster-${{ matrix.config.name }}.zip"
              
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          ${{ matrix.config.python }} -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: ${{ matrix.config.python }} compile.py

      - name: Zip App
        run: ${{ matrix.config.cmds }}

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: "OpenPoster-${{ matrix.config.name }}.zip"
          path: "dist/OpenPoster-${{ matrix.confing.name }}.zip"
